version: '3'
services:
  con_opstk_api_server:
    network_mode: "host"
    build: 
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.api_server
    ports:
      - "42356:42356"
    stop_signal: SIGINT
    volumes:
      - /var/log/concertim-openstack-service:/app/var/log
      - data_vol:/app/var/data
      - /etc/concertim-openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml

  con_opstk_metrics:
    network_mode: "host"
    build: 
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.metrics
    volumes:
      - /var/log/concertim-openstack-service:/app/var/log
      - data_vol:/app/var/data
      - /etc/concertim-openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml

#  con_opstk_updates_aio:
#    network_mode: "host"
#    build: 
#      context: .
#      dockerfile: ./Dockerfiles/Dockerfile.updates_aio
#    volumes:
#      - /var/log/concertim-openstack-service:/app/var/log
#      - data_vol:/app/var/data
#      - /etc/concertim-openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml

  con_opstk_updates_bulk:
    network_mode: "host"
    build: 
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.updates_bulk
    volumes:
      - /var/log/concertim-openstack-service:/app/var/log
      - data_vol:/app/var/data
      - /etc/concertim-openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml


  con_opstk_billing:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.billing
    volumes:
      - /var/log/concertim-openstack-service:/app/var/log
      - data_vol:/app/var/data
      - /etc/concertim-openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml
  
volumes:
  data_vol:
