# MAIN CONFIG
billing_platform: "killbill"
cloud_type: "openstack"
message_queue: "rmq"
log_level: "DEBUG"

# CONCERTIM
concertim:
    concertim_url: "https://host.concertim"
    concertim_username: "admin"
    concertim_password: "password"
    default_rack_height: 42

# CLOUD
openstack:
    auth_url: "http://host:35357/v3"
    admin_user_id: "admin"
    admin_user_password: "password"
    admin_project_id: "id"

# MESSAGE QUEUE
rmq:
    rmq_username: "openstack"
    rmq_password: "password"
    rmq_address : "host"
    rmq_port : "5672"
    rmq_path : "/"

# BILLING PLATFORM
killbill:
    api_host: "http://host.killbill:8080"
    username: "admin"
    password: "password"
    apikey: "key"
    apisecret: "secret"
    plan_name: "openstack-standard-monthly"