log_level: "DEBUG"
openstack:
        auth_url: "https://example.com:35357/v3"
        username: "admin"
        password: "password123"
        project_id: "123456789abcdf"
        project_domain_name: "default"
        user_domain_name: "default"
rmq:
        rmq_username: "openstack"
        rmq_password: ""
        rmq_address : ""
        rmq_port : "5672"
        rmq_path : "/"
concertim:
        concertim_url: "https://command.concertim.alces-flight.com/"
        concertim_username: "admin"
        concertim_password: "admin"
        default_rack_height: 20
